const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const http = require('node:http')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const {
  cleanMessage,
  confirmAnonymousEvent,
  prepareAnonymousEvent,
  readQueuedEventCount,
  reportAnonymousEvent,
  telemetryEnabled,
} = require('../bin/no-author.js')

const emptyConfig = { emails: new Set(), lines: new Set() }

test('removes known AI co-author trailers', () => {
  const message = `Fix the thing

Co-authored-by: Cursor <cursoragent@cursor.com>
Co-Authored-By: Claude <noreply@anthropic.com>
Co-authored-by: Codex <noreply@openai.com>
Co-authored-by: Gemini <gemini-code-assist@google.com>
Co-authored-by: aider (sonnet) <aider@aider.chat>
Co-authored-by: Copilot <198982749+Copilot[bot]@users.noreply.github.com>
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 6)
})

test('preserves human co-authors', () => {
  const message = `Fix the thing

Co-authored-by: Claude Dupont <claude@example.com>
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, message)
  assert.equal(result.removed, 0)
})

test('removes Claude attribution and session lines', () => {
  const message = `Fix the thing

🤖 Generated with Claude Code
Claude-Session: https://claude.ai/code/session_123
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 2)
})

test('supports configured email identities and exact lines', () => {
  const config = {
    emails: new Set(['agent@example.com']),
    lines: new Set(['Generated by Internal Agent']),
  }
  const message = `Fix the thing

Co-authored-by: Internal Agent <agent@example.com>
Generated by Internal Agent
`

  const result = cleanMessage(message, config)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 2)
})

test('allows repository-level telemetry opt-out', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'no-author-'))
  fs.writeFileSync(
    path.join(directory, '.no-author.json'),
    '{"telemetry":false}\n',
  )

  try {
    assert.equal(telemetryEnabled(directory), false)
  } finally {
    fs.rmSync(directory, { recursive: true, force: true })
  }
})

test('keeps an anonymous event queued until the counter accepts it', async () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'no-author-'))
  const previousEndpoint = process.env.NO_AUTHOR_ENDPOINT
  const previousTelemetry = process.env.NO_AUTHOR_TELEMETRY
  let server

  execFileSync('git', ['init', '--quiet', directory])
  delete process.env.NO_AUTHOR_TELEMETRY

  try {
    prepareAnonymousEvent(directory)
    confirmAnonymousEvent(directory)
    assert.equal(readQueuedEventCount(directory), 1)

    process.env.NO_AUTHOR_ENDPOINT = 'http://127.0.0.1:1'
    await reportAnonymousEvent(directory)
    assert.equal(readQueuedEventCount(directory), 1)

    server = http.createServer((request, response) => {
      assert.equal(request.method, 'POST')
      response.writeHead(201).end()
    })
    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))

    process.env.NO_AUTHOR_ENDPOINT = `http://127.0.0.1:${server.address().port}`
    await reportAnonymousEvent(directory)
    assert.equal(readQueuedEventCount(directory), 0)
  } finally {
    await new Promise((resolve) => server?.close(resolve) ?? resolve())
    fs.rmSync(directory, { recursive: true, force: true })

    if (previousEndpoint === undefined) delete process.env.NO_AUTHOR_ENDPOINT
    else process.env.NO_AUTHOR_ENDPOINT = previousEndpoint

    if (previousTelemetry === undefined) delete process.env.NO_AUTHOR_TELEMETRY
    else process.env.NO_AUTHOR_TELEMETRY = previousTelemetry
  }
})
