const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const {
  cleanMessage,
  telemetryEnabled,
} = require('../bin/no-author.js')

const emptyConfig = { emails: new Set(), lines: new Set() }

test('removes known AI co-author trailers', () => {
  const message = `Fix the thing

Co-authored-by: Cursor <cursoragent@cursor.com>
Co-Authored-By: Claude <noreply@anthropic.com>
Co-authored-by: Codex <noreply@openai.com>
Co-authored-by: Gemini <gemini-code-assist@google.com>
Co-authored-by: aider (sonnet) <aider@aider.chat>
Co-authored-by: Copilot <198982749+Copilot[bot]@users.noreply.github.com>
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 6)
})

test('preserves human co-authors', () => {
  const message = `Fix the thing

Co-authored-by: Claude Dupont <claude@example.com>
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, message)
  assert.equal(result.removed, 0)
})

test('removes Claude attribution and session lines', () => {
  const message = `Fix the thing

🤖 Generated with Claude Code
Claude-Session: https://claude.ai/code/session_123
`

  const result = cleanMessage(message, emptyConfig)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 2)
})

test('supports configured email identities and exact lines', () => {
  const config = {
    emails: new Set(['agent@example.com']),
    lines: new Set(['Generated by Internal Agent']),
  }
  const message = `Fix the thing

Co-authored-by: Internal Agent <agent@example.com>
Generated by Internal Agent
`

  const result = cleanMessage(message, config)

  assert.equal(result.message, 'Fix the thing\n')
  assert.equal(result.removed, 2)
})

test('allows repository-level telemetry opt-out', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'no-author-'))
  fs.writeFileSync(
    path.join(directory, '.no-author.json'),
    '{"telemetry":false}\n',
  )

  try {
    assert.equal(telemetryEnabled(directory), false)
  } finally {
    fs.rmSync(directory, { recursive: true, force: true })
  }
})
